### ISSUE TITLE
!filter User Level

### ISSUE THREAD

**Issue by MRVDOG** [7thAce/AcebotsIII#1]
Just to let you know the !filter command appears to be open to everyone, as I just found out when a sub sent "!filter 3 = perma ban" intending to warn people what a lvl 3 filter does, only to find out it added "= perma ban" to the filter list, I feel like this should be mod only, also would be nice for Acebots to send a message after "!delfilter" so mods know if a filter was removed

**Comment by 7thAce** [comment]
Resolved in the current running version.  I will push an update when I finish with school this semester.  If you're running a version, remove the ; after the if(hasAccess) in the plugin.

Thanks for the catch!
