### ISSUE TITLE
Yo Bot is not working correctly!

### ISSUE THREAD

**Issue by BigBrainAFK** [7thAce/AcebotsIII#2]
when someone tries to use !uptime and when the bot starts up the bot makes some java errors.

Maybe its due to the fact that twitch stream that are offline wont give the created_at info anymore but they will have a "stream" key which is null so pls fix.

**Comment by Szil** [comment]
Hey! 

https://github.com/Szil/AcebotsIII/releases/tag/Jar-1.0.1-Oct28

With this release !uptime should work as intended. 
When 7thAce have time can merge back the changes to this project.

Szil
